openapi: 3.0.0
info:
  title: URL Shortener API
  version: "1.0.0"
  description: >
    A URL shortener built with TypeScript and Node.js.
    It provides user registration, authentication, URL shortening,
    redirection, and admin analytics endpoints.

servers:
  - url: http://localhost:3000

paths:
  /register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: User registered successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessMessage'
        '400':
          description: Bad Request. Missing fields or duplicate username.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /login:
    post:
      summary: Log in an existing user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Login successful. Returns a JWT token.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '400':
          description: Missing required fields.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Invalid credentials.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /shorten:
    post:
      summary: Shorten a URL (requires authentication)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShortenRequest'
      responses:
        '201':
          description: URL shortened successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShortenResponse'
        '401':
          description: Authentication error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /{shortCode}:
    get:
      summary: Redirect to the original URL
      parameters:
        - in: path
          name: shortCode
          schema:
            type: string
          required: true
          description: The short code of the URL.
      responses:
        '302':
          description: Redirect to the original URL.
          headers:
            Location:
              description: Original URL location.
              schema:
                type: string
        '404':
          description: URL not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /admin/analytics:
    get:
      summary: Get analytics data (admin only)
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Returns analytics data.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Analytics'
        '401':
          description: Unauthorized.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden – Admins only.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    RegisterRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
        adminPassword:
          type: string
      required:
        - username
        - password
    LoginRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
        adminPassword:
          type: string
    LoginResponse:
      type: object
      properties:
        message:
          type: string
        token:
          type: string
    ShortenRequest:
      type: object
      properties:
        originalUrl:
          type: string
      required:
        - originalUrl
    ShortenResponse:
      type: object
      properties:
        shortUrl:
          type: string
    Analytics:
      type: object
      properties:
        totalRequests:
          type: integer
        requestsPerWeek:
          type: array
          items:
            type: object
            properties:
              week:
                type: string
              count:
                type: integer
        requestsPerMonth:
          type: array
          items:
            type: object
            properties:
              month:
                type: string
              count:
                type: integer
        deviceDistribution:
          type: object
          additionalProperties:
            type: integer
        osDistribution:
          type: object
          additionalProperties:
            type: integer
        geographicalDistribution:
          type: object
          additionalProperties:
            type: integer
        topUrls:
          type: array
          items:
            type: object
            properties:
              original_url:
                type: string
              count:
                type: integer
        averageRequests:
          type: number
    SuccessMessage:
      type: object
      properties:
        message:
          type: string
    Error:
      type: object
      properties:
        error:
          type: string

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT